[package]
name = "rosalind-algo-solutions"
version = "0.1.1"
authors = ["Oleg Kulyk <helh.saintman@gmail.com>"]

[dependencies]
num = "0.1"
docopt = "*"
rustc-serialize = "0.3"
rosalind-algo = { git = "https://github.com/eleidan/rosalind-algo-rs.git" }
